---
apiVersion: v1
kind: Pod
metadata:
   name: setnever
spec:
   containers:
         - name: restartnever
           image: nginx
           ports:
             - containerPort: 80
           command: ["sleep","30s"]
   restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
   name: any
spec:
   containers:
         - name: start
           image: nginx
           ports:
             - containerPort: 80
         - name: mycontainer
           image: alpine
           ports:
             - containerPort: 80



---
apiVersion: v1
kind: Pod
metadata:
   name: init
spec:
    initContainers:
           - name: initcont
             image: tomcat:9.0.70-jdk8-corretto-al2
             ports:
                - containerPort: 8080

    containers:
           - name: cont
             image: tomcat:9.0.70-jdk8-corretto-al2
             ports:
                - containerPort: 8080

---
##this is failed yaml file
apiVersion: v1
kind: ReplicationController
metadata:
    name: replication
spec:
    selector:
      matchLabels:
          app: replication
    replicas: 3
    minReadySeconds: 15  
    template: 
        metadata:
          name: replication
        spec:
          containers:
               - name: container1
                 image: tomcat:9.0.70-jdk8-corretto-al2
                 ports:
                   - containerPort: 8080


---
#labels for k8s
apiVersion: v1
kind: Pod
metadata:
    name: nginx1
    labels:
       app: nginx1
       version: "1.23"
spec:
    containers:
         - name: container1
           image: nginx:1.23
           ports:
              - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
    name: nginx2
    labels:
       app: nginx2
       version: "1.24"
spec:
    containers:
         - name: container2
           image: nginx:1
           ports:
              - containerPort: 80

---


         